---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: ghcr.io/samis-group/nginx:latest
          imagePullPolicy: Always # Always grab latest when pipeline finishes building
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 2Mi
              cpu: "0.001"
          env:
            - name: TZ
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: TZ
            - name: NGINX_HOST
              value: shaklab.com
            - name: NGINX_PORT
              value: "80"
      imagePullSecrets:
        - name: github-registry-credentials
