# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # General configuration
  config.vm.box = "generic/ubuntu2004"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
      v.memory = 4096
      v.cpus = 2
      v.linked_clone = true
  end

  # Main Node 1
  config.vm.define "k3sm1" do |k3sm1|
      k3sm1.vm.hostname = "k3sm1"
      k3sm1.vm.network "private_network", bridge: "Realtek PCIe 2.5GbE Family Controller", ip: "10.10.0.30"
  end

  # Main Node 2
  config.vm.define "k3sm2" do |k3sm2|
      k3sm2.vm.hostname = "k3sm2"
      k3sm2.vm.network "private_network", bridge: "Realtek PCIe 2.5GbE Family Controller", ip: "10.10.0.31"
  end

  # Worker Node 1
  config.vm.define "k3sn1" do |k3sn1|
    k3sn1.vm.hostname = "k3sn1"
    k3sn1.vm.network "private_network", bridge: "Realtek PCIe 2.5GbE Family Controller", ip: "10.10.0.35"
  end
  
  # Worker Node 2
  config.vm.define "k3sn2" do |k3sn2|
    k3sn2.vm.hostname = "k3sn2"
    k3sn2.vm.network "private_network", bridge: "Realtek PCIe 2.5GbE Family Controller", ip: "10.10.0.36"
  end
  
  # Worker Node 3
  config.vm.define "k3sn3" do |k3sn3|
      k3sn3.vm.hostname = "k3sn3"
      k3sn3.vm.network "private_network", bridge: "Realtek PCIe 2.5GbE Family Controller", ip: "10.10.0.37"
  end

  config.vm.provision "ansible", type: "ansible", run: "never" do |ansible|
      ansible.playbook = "../playbook_k3s.yml"
      ansible.limit = "all"
      # ansible.groups = {
      #   "k3s_main" => ["k3sm1", "k3sm2"],
      #   "k3s_node" => ["k3sn1", "k3sn2", "k3sn3"],
      #   "k3s:children" => ["k3s_main", "k3s_node"],
      #   "k3s:vars" => {"k3s_version" => "v1.23.4+k3s1",
      #                          "ansible_user" => "vagrant",
      #                          "systemd_dir" => "/etc/systemd/system",
      #                          "flannel_iface" => "eth1",
      #                          "apiserver_endpoint" => "10.10.0.40",
      #                          "k3s_token" => "supersecret",
      #                          "extra_server_args" => "--node-ip={{ ansible_eth1.ipv4.address }} --flannel-iface={{ flannel_iface }} --no-deploy servicelb --no-deploy traefik",
      #                          "extra_agent_args" => "--flannel-iface={{ flannel_iface }}",
      #                          "kube_vip_tag_version" => "v0.4.2",
      #                          "metal_lb_speaker_tag_version" => "v0.12.1",
      #                          "metal_lb_controller_tag_version" => "v0.12.1",
      #                          "metal_lb_ip_range" => "10.10.0.41-10.10.0.49",
      #                          "retry_count" => "30"}
      # }
      # ansible.host_vars = {
      #   "k3sn1" => {
      #     "server_init_args" => "--cluster-init --token {{ k3s_token }} {{ extra_server_args | default('') }}"
      #   },
      #   "k3sn2" => {
      #     "server_init_args" => "--server https://10.10.0.30:6443 --token {{ k3s_token }} {{ extra_server_args | default('') }}"
      #   },
      #   "k3sn3" => {
      #     "server_init_args" => "--server https://10.10.0.30:6443 --token {{ k3s_token }} {{ extra_server_args | default('') }}"
      #   }
      # }
  end
end
