---
nas_dir: "/mnt/pve/NAS"
img_dir: "{{ nas_dir }}/template/iso"
truenas_iso_url: https://download.truenas.com/TrueNAS-SCALE-Bluefin/22.12.3.1/TrueNAS-SCALE-22.12.3.1.iso

truenas_vm:
  name: TrueNAS
  cpu: host
  id: 100
  storage: nvme
  memory: 8192 # ram for each VM in MBz

# Find this out with `lsblk -o +MODEL,SERIAL`. Then find the device in `/dev/disk/by-id/`
passthrough_disks: "{{ lookup('env', 'PASSTHROUGH_DISKS') | from_yaml }}" # Passed in from doppler
