---
- name: Provision VM(s) on Proxmox Host From Template
  hosts: "{{ target_host_group }}"
  gather_facts: false   # Because they don't exist yet
  become: true
  roles:
    - role: ../roles/proxmox/provision-vm-from-template
      when: provision_vms
      tags: ["provision_vms"]
      delegate_to: "{{ target_proxmox_host }}"
    - role: ../roles/proxmox/vm-post-tasks
      when: provision_vms
      tags: ["provision_vms"]
