---
# ------------ #
# DNS For Host #
# ------------ #
- name: Cloudflare DNS for Proxmox host
  hosts: localhost
  # Special tag "always" -> https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#special-tags-always-and-never
  tags: ["always"]
  gather_facts: false
  tasks:
    - name: Setup cloudflare DNS for Proxmox Host
      community.general.cloudflare_dns:
        zone: "{{ domain_name }}"
        record: "{{ groups['tnas'][0] | default('tnas01') }}"
        type: A
        value: "{{ tnas_host }}"
        api_token: "{{ cloudflare_api_token }}"

# ----------------------------------- #
# Pre-tasks run before anything else! #
# ----------------------------------- #
- name: Pre-all / Proxmox
  hosts: tnas
  # Special tag "always" -> https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#special-tags-always-and-never
  tags: ["always"]
  gather_facts: false
  tasks:
    - name: Pre-all / Proxmox
      ansible.builtin.import_tasks: ../tasks/pre-all.yml

- name: Configure Proxmox
  hosts: tnas

  pre_tasks: &pre_tasks   # Anchors to re-use the code later. No point duplicating code.

    # This is to get the PUID and PGID variables to use later in multiple areas
    - name: Get user info or create a user if one doesn't exist
      ansible.builtin.import_tasks: ../tasks/linux/pre_tasks.yml
      tags: ["always"]

  handlers:

    - name: Include proxmox handlers
      ansible.builtin.import_tasks: ../handlers/proxmox.yml

  roles:

    - role: ironicbadger.proxmox_nag_removal
    - role: prometheus.prometheus.node_exporter
    # Run pre-tasks on Proxmox host (Mainly just check connectivity)
    # - role: ../roles/proxmox/pre-tasks
    # - role: ../roles/proxmox/configure-for-lxcs
    # - role: ../roles/proxmox/install-os-packages
    #   when: install_os_packages
    #   tags: ["install_os_packages"]
    # - role: ../roles/proxmox/nas-nfs
    # - role: ../roles/proxmox/copy-files
    #   when: copy_files
    #   tags: ["copy_files"]
    # - role: nununo.proxmox_haos_install
    #   when: proxmox_haos_install
    #   tags: ["proxmox_haos_install"]
    #   vars:
    #     haos_proxmox_api_user: "{{ proxmox_api_user }}"
    #     haos_proxmox_api_password: "{{ proxmox_api_pass }}"
    #     haos_proxmox_description: "Home Assistant"
    #     # haos_proxmox_mac_address: 'AB:CD:EF:12:34:56'
    #     haos_proxmox_name: HomeAssistsant
    #     haos_proxmox_node: "{{ proxmox_node }}"
    #     haos_proxmox_storage: local
