---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: volsync
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: volsync
      version: 0.8.0
      sourceRef:
        kind: HelmRepository
        name: backube
        namespace: flux-system
      interval: 1h
  values:
    manageCRDs: true
    metrics:
      disableAuth: true
    image:
      repository: &image ghcr.io/onedr0p/volsync
      tag: &tag 0.8.0
    restic:
      repository: *image
      tag: *tag
    resources:
      limits:
        cpu:
        memory: 300Mi
      requests:
        cpu: 15m
        memory: 64Mi
