---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ozbargain-secrets
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: homelab-dev-container
  target:
    name: ozbargain-secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: "OZBARGAIN"
