---
# yaml-language-server: $schema=https://kubernetes-schemas.haraldkoch.ca/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-volsync
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-snapshot-controller
    - name: cluster-apps-external-secrets-stores
  interval: 1h
  path: ./kubernetes/home/apps/kube-system/volsync/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  # wait: true
  timeout: 2m
