---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            # supplementalGroups:
            #   - 34
            #   - 100
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: docker.io/filebrowser/filebrowser
              tag: v2.27.0
              pullPolicy: IfNotPresent
            env:
              TZ:
                valueFrom:
                  secretKeyRef:
                    name: common-secrets
                    key: TZ
              FB_DATABASE: /config/filebrowser.db
              FB_ROOT: /data
              FB_LOG: stdout
              FB_NOAUTH: true
              FB_PORT: &port 30044
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi

    service:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: filebrowser.shaklab.com, files.shaklab.com
          external-dns.alpha.kubernetes.io/target: ipv4.shaklab.com
        ports:
          http:
            port: *port

    persistence:
      config:
        enabled: true
        existingClaim: filebrowser-config
      nfs-nas-data:
        type: nfs
        server: 10.10.0.3
        path: /mnt/rust/backup_from_syno/NAS_1
        advancedMounts:
          main:
            main:
              - path: /data

    # ingress:
    #   main:
    #     enabled: true
    #     className: "traefik"
    #     annotations:
    #       cert-manager.io/cluster-issuer: letsencrypt-production
    #       traefik.ingress.kubernetes.io/router.entrypoints: websecure
    #       # traefik.ingress.kubernetes.io/router.middlewares: "network-chain-global-auth@kubernetescrd"
    #       traefik.ingress.kubernetes.io/router.middlewares: network-chain-external@kubernetescrd
    #       external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    #       external-dns.alpha.kubernetes.io/target: ingress.${INGRESS_DOMAIN}
    #       external-dns/is-public: "true"
    #       external-dns/powerdns: "true"
    #     hosts:
    #       - host: *host-cluster
    #         paths:
    #           - path: /
    #             pathType: Prefix
    #             service:
    #               name: main
    #               port: http
    #       - host: &host "filebrowser.${INGRESS_DOMAIN}"
    #         paths:
    #           - path: /
    #             pathType: Prefix
    #             service:
    #               name: main
    #               port: http
    #     tls:
    #       - secretName: tls.filebrowser
    #         hosts:
    #           - *host-cluster
    #           - *host
