---
lxc_ip_address: "{{ vm_network }}70"  # Required

lxc:
  # image: "ubuntu-22.04-standard_22.04-1_amd64.tar.zst"
  id: 170 # Required
  description: "Machine to do development on."
  storage: "local"
  disk: "20"  # Size of disk (in GB)
  swap: 0
  netif: '{"net0":"name=eth0,gw={{ vm_gateway }},ip={{ lxc_ip_address }}/{{ vm_netmask }},bridge={{ lxc_defaults.network_device }}"}'
  features:
    - nesting=1
    - mount=nfs
  memory: "4096" # ram for each VM in MB
  unprivileged: true
