---
vm_ip_address: "{{ vm_network }}24"  # Required

vm:
  # name: k3s-vm1   # Default is ansible magic var `inventory_hostname_short` if omitted
  ipconfig:
    ipconfig0: "ip={{ vm_ip_address }}/{{ vm_netmask }},gw={{ vm_gateway }}"
  id: 106   # Required
  hdd_size: "100G"
  cpu: host
  cores: 4
  memory: 24000
  template: "UbuntuCloud-jammy-22.04"   # Specify a template
  storage: "local"
