---
lxc_ip_address: "{{ vm_network }}50"  # Required

lxc:
  image: "debian-10-turnkey-openldap_16.1-1_amd64.tar.gz" # Default User = root
  id: 220 # Required
  description: "LDAP Server"
  netif: '{"net0":"name=eth0,gw={{ vm_gateway }},ip={{ lxc_ip_address }}/{{ vm_netmask }},bridge={{ lxc_defaults.network_device }}"}'
