apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-daemon-config
  namespace: actions-runner-system
data:
  daemon.json: |
    {
      "mtu": 1400
    }
# Add this to avoid rate limiting
# "registry-mirrors": ["http://registry.arc-runners.svc.local.configit:5000"]
