---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: snapshot-controller
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
      interval: 1h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    replicaCount: 3
    serviceMonitor:
      create: true
    # volumeSnapshotClasses:
    #   - name: csi-ceph-blockpool
    #     driver: rook-ceph.rbd.csi.ceph.com
    #     annotations:
    #       snapshot.storage.kubernetes.io/is-default-class: "true"
    #     parameters:
    #       clusterID: rook-ceph
    #       csi.storage.k8s.io/snapshotter-secret-name: rook-csi-rbd-provisioner
    #       csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph
    #     deletionPolicy: Delete
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: snapshot-validation-webhook
#   namespace: kube-system
# spec:
#   interval: 1h
#   chart:
#     spec:
#       chart: snapshot-validation-webhook
#       version: 1.7.4
#       sourceRef:
#         kind: HelmRepository
#         name: piraeus
#         namespace: flux-system
#       interval: 1h
#   install:
#     crds: Skip
#   upgrade:
#     crds: Skip
#   dependsOn:
#     - name: snapshot-controller
