---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helm-release.yaml
  - ./secrets.yaml
configMapGenerator:
  - name: cloudflare-ddns-configmap
    files:
      - ./scripts/cloudflare-ddns.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
