---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name cloudflare-ddns-secret
  namespace: default
spec:
  secretStoreRef:
    name: homelab-dev-container
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      templateFrom:
        - configMap:
            name: cloudflare-ddns-configmap
            items:
              - key: cloudflare-ddns.sh
  dataFrom:
    - find:
        name:
          regexp: "^CLOUDFLARE"
