---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/onedr0p/jellyfin
      tag: "10.8.11"
    env:
      TZ:
        valueFrom:
          secretKeyRef:
            name: common-secrets
            key: TZ
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "10.10.0.83"
        externalTrafficPolicy: Local
        annotations:
          external-dns.alpha.kubernetes.io/hostname: jellyfin-lb.shaklab.com
          external-dns.alpha.kubernetes.io/target: 10.10.0.83
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        # externalIPs:
        #   - ${JELLYFIN_IP}
        ports:
          http:
            port: &port 8096
      web:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: jellyfin.shaklab.com, jfin.shaklab.com
          external-dns.alpha.kubernetes.io/target: ipv4.shaklab.com
        ports:
          web:
            port: *port
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config
      transcode:
        enabled: true
        type: emptyDir
      nfs-nas-movies:
        enabled: true
        mountPath: /media/movies
        path: /volume1/docker/data/media/movies
        server: 10.10.0.2
        type: nfs
      nfs-nas-tv:
        enabled: true
        mountPath: /media/tv
        path: /volume1/docker/data/media/tv
        server: 10.10.0.2
        type: nfs
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      # supplementalGroups:
      #   - 44  # video
      #   - 109  # render
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /health
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes
      startup:
        enabled: false
    # nodeSelector:
    #   intel.feature.node.kubernetes.io/gpu: "true"
    resources:
      requests:
        cpu: 0.001
        memory: 256M
        # gpu.intel.com/i915: 1
      limits:
        memory: 3Gi
        # gpu.intel.com/i915: 1
    # ingress:
    #   main:
    #     enabled: true
    #     annotations:
    #       external-dns.home.arpa/enabled: "true"
    #       cert-manager.home.arpa/enabled: "true"
    #     hosts:
    #       - host: &host jellyfin.${DOMAIN}
    #         paths:
    #           - path: /
    #             pathType: Prefix
    #     tls:
    #       - hosts:
    #           - *host
    #         secretName: jellyfin-tls
