---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rook-ceph
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-external-secrets-stores
  targetNamespace: storage
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/home/apps/storage/rook-ceph/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: true
  interval: 1h
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rook-ceph-cluster
  namespace: flux-system
spec:
  targetNamespace: storage
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: rook-ceph
  path: ./kubernetes/home/apps/storage/rook-ceph/cluster
  prune: false
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
  interval: 1h
  retryInterval: 1m
  timeout: 15m
