- name: Check existence of container
  command: podman container exists qbittorrent
  register: container_exists
  failed_when: container_exists.rc > 1

# - name: Create media directories
#   file:
#     path: '{{ mediadir }}/{{ item }}'
#     state: directory
#   loop:
#     - downloading
#     - completed
#     - movies
#     - shows

- name: Create container
  command: >
    podman create --name=qbittorrent
    --userns=""
    -e PUID=0
    -e PGID=0
    -e WEBUI_PORT=8080
    -p 8080:8080
    -p 6881:6881
    -p 6881:6881/udp
    -v qbittorrent-config:/config
    docker.io/linuxserver/qbittorrent
  when: container_exists.rc == 1
  # -v {{ mediadir }}:/media:z

# - name: Configure firewalld
#   firewalld:
#     port: '{{ item }}'
#     state: enabled
#     immediate: true
#     permanent: true
#   loop:
#     - 8080/tcp
#     - 6881/tcp
#     - 6881/udp
#   become: true

- name: Install systemd service
  copy:
    src: qbittorrent.service
    dest: '/usr/lib/systemd/system/qbittorrent.service'
    mode: 0644

- name: Enable systemd service
  systemd:
    name: qbittorrent.service
    state: started
    enabled: true
    daemon_reload: true
