- name: Check existence of container
  command: podman container exists qbittorrent
  register: container_exists
  failed_when: container_exists.rc > 1

- name: Create media directories
  file:
    path: '{{ mediadir }}/{{ item }}'
    state: directory
  loop:
    - downloading
    - completed
    - movies
    - shows

- name: Create container
  command: >
    podman create --name=qbittorrent
    --userns=""
    -e PUID=0
    -e PGID=0
    -e WEBUI_PORT=8080
    -p 8080:8080
    -p 6881:6881
    -p 6881:6881/udp
    -v qbittorrent-config:/config
    -v {{ mediadir }}:/media:z
    docker.io/linuxserver/qbittorrent
  when: container_exists.rc == 1

- name: Configure firewalld
  firewalld:
    port: '{{ item }}'
    state: enabled
    immediate: true
    permanent: true
  loop:
    - 8080/tcp
    - 6881/tcp
    - 6881/udp
  become: true

- name: Install systemd service
  copy:
    src: qbittorrent.service
    dest: '{{ configdir }}/systemd/user/qbittorrent.service'
    mode: 0644

- name: Enable systemd service
  systemd:
    name: qbittorrent.service
    scope: user
    state: started
    enabled: true
    daemon_reload: true

- name: Install easymode config
  copy:
    src: qbittorrent.yml
    dest: "{{ easymodeconfig }}/"
  when: easymodeconfig is defined
