name: Docker Image - Actions Runner Base

on:
  push:
    paths:
      - "docker/actions-runner-base/**"
    branches:
      - 'main'
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    uses: samis-group/actions-workflows/.github/workflows/docker/build-and-publish-image.yaml@main
    with:
      image_name: actions-runner-base
