name: Debug Variables

on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: [arc-runner-set-ubuntu-base]

    steps:
    - name: Debug github context
      run: |
        # Debug the secret or environment variable by printing its value
        echo "The github actor is: ${{ github.actor }}"
        echo "The github repo owner is: ${{ github.repository_owner }}"

    - run: echo "🎉 This job used my self hosted runner!"

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # otherwise, you will failed to push refs to dest repo
