name: Docker Image - Workstation

on:
  push:
    paths:
      - 'docker/homelab-workstation/**'
      - 'provision/ansible/requirements.yml'
      - 'provision/ansible/roles/requirements.yml'
      - 'requirements.txt'
    # branches:
    #   - 'main'
    # tags:
    #   - 'v*'
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    uses: .github/workflows/docker-image-reusable-workflow.yaml@main
    with:
      image_name: homelab-workstation
