name: Docker Image - Actions Runner Base

on:
  push:
    paths:
      - "docker/actions-runner-base/**"
    # branches:
    #   - 'main'
    # tags:
    #   - 'v*'
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    uses: .github/workflows/docker-image-reusable-workflow.yaml
    with:
      image_name: actions-runner-base
