name: Docker Image - Workstation

on:
  push:
    paths:
      - 'docker/homelab-workstation/**'
      - 'provision/ansible/requirements.yml'
      - 'provision/ansible/roles/requirements.yml'
      - 'requirements.txt'
    branches:
      - 'main'
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    uses: samis-group/actions-workflows/.github/workflows/docker/build-and-publish-image.yaml@main
    with:
      image_name: homelab-workstation
      platforms: 'linux/amd64,linux/arm64'
