name: Docker Image - Workstation

on:
  push:
    paths:
      - 'docker/workstation/**'
      - 'provision/ansible/requirements.yml'
      - 'provision/ansible/roles/requirements.yml'
      - 'requirements.txt'
    branches:
      - 'main'
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    uses: samis-group/actions-workflows/.github/workflows/docker-build-and-publish.yaml@main
    with:
      image_name: workstation
      platforms: 'linux/amd64,linux/arm64'
      dockerfile: docker/workstation/Dockerfile
      # run_on_runners: "ubuntu-latest" # Use public runner for public project if you would like
